language: go
go:
- 1.13.x
env:
- GO111MODULE=on
install:
- go get -v ./...
script:
- "./_bin/test.sh"
before_deploy:
- "./_bin/build.sh darwin ${TRAVIS_TAG}"
- "./_bin/build.sh linux ${TRAVIS_TAG}"
deploy:
  provider: releases
  api_key:
    secure: dDafGtm1CpthsN3pHyciGvq+n7OiFJfiq0A32/FujYz9aBx8w4ZxMH8X4wiqw1Cy0SVRKx7Z35gVBBrYM0PZQ/Anpkm0epnZ6RfoGOkpgklKvK6T27pLYlwMnHBVPDbMVluD3I0XRvVT1dRuT0eMWsdnGy6Dh07BJtnKlsRdAbMaTlWI4OkdpS1/WoOUkxs5WuGtJ3qY7KjF0EJj21yC/8kYqrKOhjKGknggJWByvcVUNA8N6xb28TM+yDHiYAuRkUrCgnM64gFlSr8C/Tt5F/I+BaOlC7U4kdcyX+6HM06vZHN2yxLKtsKjuyhZK8D7F1Xa1heisH44jTVCg7hnwRasGKzkc9PHB+eeCTcnKjFTREgMmkEVQHD8YyJKYPxtp0ouS7Srtb/5yylUbijd8JyY8wXbUdjbnRWTYuauDajUiPM6rq/iXIpzbsM5emWRhQ14H7DMzlZnEI8DvovB0/WEGpd+Z3u182VAlgJrbdgyqNqeTRyPEjo1jOLT8hUM6lKSDXI4mMm+DjUGMV9mCkVQgFdhXlkMjRcNranNi3aa6QddwLnb5O5SOgNwkEeRuzX/opG0tC3tkbiMbijIgeE9CMZbJWJGGrGl/6KzcB3D2H/SEMlSx8ONLCAWmkRniFsEwDOc/4OJDA2x4lEhkpprzKonryqoJ4a9yBgHOBo=
  file: 
    - "inout_darwin_${TRAVIS_TAG}"
    - "inout_linux_${TRAVIS_TAG}"
  on:
    tags: true
    repo: zoomio/inout
